<?php

namespace app\modules\anniuchongyang\controllers;

use app\modules\anniuchongyang\models\AnniuchongyangAnswer;
use app\modules\anniuchongyang\models\AnniuchongyangQuestion;
use Yii;
use app\modules\anniuchongyang\BL\StatusTransfer;
use yii\helpers\ArrayHelper;
use yii\helpers\Json;
use yii\web\Controller;
use yii\helpers\Url;
use app\modules\anniuchongyang\BL\Lottery;


/**
 * Default controller for the `zhuanpan` module
 */
class DefaultController extends Controller
{
    public $enableCsrfValidation = false;

    /**
     * Renders the index view for the module
     * @return string
     */
    public function init()
    {
        parent::init();
        $this->view->title = Yii::$app->params['site_name'];
    }

    public function beforeAction($action)
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(Url::to(['oauth/index', 'forword' => urlencode(Url::current([], true))], true))->send();
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub

    }

    /**
     * 重阳节诗词大赛
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');

    }

    /**
     * 问题
     * @param int $category 问题分类
     * @return string
     */
    public function actionQuestion($category = 1)
    {
        $user = Yii::$app->user->identity->id;
        //查找已经做过的题目
        $already = AnniuchongyangAnswer::find()
            ->select(['question_id'])
            ->distinct()
            ->where(['user_id' => $user])
            ->andWhere(['question_category' => $category])
            ->joinWith('question')
            ->all();
        if ($already) {
            foreach ($already as $k => $v) {
                $question_id[] = $v->question_id;
            }
            //查找未做过的题目
            $question = AnniuchongyangQuestion::Rest($question_id, $category, 5);
            $rest_count = count($question);

            if ($rest_count <= 5 && $rest_count != 0) {

                $all_question = AnniuchongyangQuestion::Question($category, 5 - $rest_count);

                $question = ArrayHelper::merge($question, $all_question);

                return Json::encode($question);
            }
        }
        $question = AnniuchongyangQuestion::Question($category, 5, 1);

        return Json::encode($question);
    }

    /**
     * 用户答题
     * @param int $question 问题
     * @param string $answer 答案
     * @return string
     */
    public function actionAnswer()
    {
        $user = Yii::$app->user->identity->id;
        $data = Yii::$app->request->get();
        $question = AnniuchongyangQuestion::Answer($data['question']);
        //保存用户答题记录
        $choice = new AnniuchongyangAnswer();
        $choice->user_id = $user;
        $choice->question_id = $data['question'];
        $choice->answer = $data['answer'];
        $choice->save();
        if (strtolower($data['answer']) == strtolower($question->right_choice)) {
            $code = 0;
        } else {
            $code = 1;
        }

        return Json::encode($code);
    }

    /**
     * 抽奖页面
     * @return string
     */
    public function actionLottery()
    {
        return $this->render('lottery');
    }

    /**
     * Renders the index view for the module 抽奖
     * @return string
     */
    public function actionLotteryRun()
    {

        // 计算今天第几天

//            if (StatusTransfer::getOrdinal() > 7) {
//                return;
//            }

        if (StatusTransfer::getToDayPid() != 0) {
            // 本日已经获奖:可抽但不会中奖
            $result = Lottery::getBad();
            StatusTransfer::markPause();
        }

        if (StatusTransfer::getToDayPid() == 0) {
            // 可以正常抽奖
            $result = Lottery::run();
        }

        $min = $result['min'];
        $max = $result['max'];
        if (is_array($min)) { //多等奖的时候
            $i = mt_rand(0, count($min) - 1);

            $result['angle'] = mt_rand($min[$i], $max[$i]);
        } else {
            $result['angle'] = mt_rand($min, $max); //随机生成一个角度
        }
        return json_encode($result);

    }

}
