<?php

namespace app\modules\anniuzhengwen\controllers;


use app\modules\anniuzhengwen\models\Article;
use app\modules\valentinesday\models\Photo;
use app\modules\anniuzhengwen\models\Vote;
use Yii;
use yii\helpers\Json;
use yii\web\Controller;
use yii\helpers\Url;
use yii\web\NotFoundHttpException;


/**
 * Default controller for the `fathersday` module
 */
class DefaultController extends Controller
{
    public $enableCsrfValidation = false;

    public function init()
    {
        parent::init();
        $this->view->title = Yii::$app->params['site_name'];
    }

    public function beforeAction($action)
    {

        if (Yii::$app->user->isGuest) {
            return $this->redirect(Url::to(['oauth/index', 'forword' => urlencode(Url::current([], true))], true))->send();
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub

    }

    /**
     * 活动首页
     * Renders the index view for the module
     * @return string
     */
    public function actionIndex()
    {
        $articles = Article::Articles();
        return $this->render('index', [
            'data' => $articles
        ]);
    }

    /**
     * 查看详情,在此页面投票
     * @param $id
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionArticle($id)
    {
        $viewData = Article::findOne($id);
        if (empty($viewData)) {
            throw new NotFoundHttpException('该文章不存在');
        }
        return $this->render('article', [
            'model' => $viewData
        ]);
    }

    /**
     * 投票操作
     * Renders the lottery view for the module
     * @return string
     */
    public function actionVote($id)
    {
        $openid = Yii::$app->user->identity->openid;

        if (($photoModel = Article::findOne(['id' => $id])) === null) {
            $res['code'] = 404;
            return json_encode($res);

        }

        $currentDay = (new \DateTime())->format('Y-m-d 00:00:00');

        $voteModel = Vote::find()->where(['>=', 'created_at', $currentDay])->andWhere(['openid' => $openid])->count();

        if ($voteModel < 3) {

            $voteModel = new Vote();

            $voteModel->openid = $openid;
            $voteModel->article_id = $photoModel->id;
            $voteModel->ip = Yii::$app->request->userIP;

            if ($voteModel->save() !== false) {
                $photoModel->vote = Vote::find()->where(['article_id' => $photoModel->id])->count();
                $photoModel->save();
            }

            $res['code'] = 200;

        } else {
            $res['code'] = 304;
        }

        return json_encode($res);
    }

    /**
     * 分享页面
     * @return string
     */
    public function actionShare()
    {
        return $this->render('share');
    }
}
