<?php

namespace app\modules\peixiaowangluo\controllers;


use Yii;
use yii\web\Controller;
use yii\helpers\Url;

/**
 * Default controller for the `Company` module
 */
class DefaultController extends Controller
{
    public $enableCsrfValidation = false;

    public function init()
    {
        parent::init();
        $this->view->title = Yii::$app->params['site_name'];
    }

    public function beforeAction($action)
    {
        if (Yii::$app->user->isGuest) {

            return $this->redirect(Url::to(['oauth/index', 'forword' => urlencode(Url::current([], true))], true))->send();
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub

    }

    /**
     * 活动首页
     * Renders the index view for the module
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

}
