<?php
/**
 * Created by PhpStorm.
 * User: Miinno-10
 * Date: 2017/9/13
 * Time: 16:43
 */

namespace app\modules\ejiaotiebiaoqian\controllers;

use app\modules\ejiaotiebiaoqian\models\EjiaotiebiaoqianFriends;
use app\modules\ejiaotiebiaoqian\models\EjiaotiebiaoqianSelflabels;
use Yii;
use yii\helpers\Json;
use yii\web\Controller;
use yii\helpers\Url;
use app\modules\ejiaotiebiaoqian\models\EjiaotiebiaoqianLabels;

class ShareController extends Controller
{
    public $enableCsrfValidation = false;

    public function init()
    {
        parent::init();
        $this->view->title = Yii::$app->params['site_name'];
    }

    public function beforeAction($action)
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(Url::to(['oauth/index', 'forword' => urlencode(Url::current([], true))], true))->send();
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub

    }

    /**
     * 标签列表查询
     * Renders the index view for the module
     * @return string
     */
    public function actionShare()
    {
        $dataProvider = EjiaotiebiaoqianLabels::LabelsLists();
        $dataProvider = $dataProvider->getModels();
        //查询分享人本身的标签
        $params = Yii::$app->request->get();
        $params['myself'] = base64_decode($params['myself'], true);
        $labels = EjiaotiebiaoqianSelflabels::MyLabels($params['myself']);
        if ($labels) {
            //根据本人的标签去查询当前朋友猜测中是否存在正确标签
            $trueLabels = EjiaotiebiaoqianFriends::GuessTrue($params['myself'], $labels->labels);
        } else {
            $trueLabels = '';
        }
        return $this->render('share', [
            'dataProvider' => $dataProvider,
            'labels' => $trueLabels,
            'myself' => $params['myself']
        ]);
    }

    /**
     * 好友猜测标签
     * @return string
     */
    public function actionGuessLabel()
    {
        $params = Yii::$app->request->get();
        //标签保存
        $model = new EjiaotiebiaoqianFriends();
        $model->friends = Yii::$app->user->identity->openid;
        $params['myself'] = base64_decode($params['myself'], true);
        $model->load($params, '');
        $model->save();
        //查询分享人本身的标签
        $labels = EjiaotiebiaoqianSelflabels::MyLabels($params['myself']);
        if ($labels) {
            //标签比较
            $selfLabel = explode(',', $labels->labels);
            $guessLabel = explode(',', $params['labels']);

            if (!array_diff($guessLabel, $selfLabel)) {
                $result = [
                    'code' => 0,
                ];
            } else {
                $result = [
                    'code' => 1,
                ];
            }
        } else {
            $result = [
                'code' => 1,
            ];
        }

        return Json::encode($result);
    }
}