<?php
/**
 * Created by PhpStorm.
 * User: Miinno-10
 * Date: 2017/9/12
 * Time: 13:43
 */
namespace app\modules\ejiaotiebiaoqian\controllers;


use app\modules\ejiaotiebiaoqian\models\EjiaotiebiaoqianFriends;
use app\modules\ejiaotiebiaoqian\models\EjiaotiebiaoqianSelflabels;
use app\modules\ejiaotiebiaoqian\models\EjiaotiebiaoqianUserinfo;
use Yii;
use app\modules\ejiaotiebiaoqian\BL\Lottery;
use app\modules\ejiaotiebiaoqian\models\EjiaotiebiaoqianLabels;
use yii\helpers\Json;
use yii\web\Controller;
use yii\helpers\Url;


/**
 * Default controller for the `fathersday` module
 */
class DefaultController extends Controller
{
    public $enableCsrfValidation = false;

    public function init()
    {
        parent::init();
        $this->view->title = Yii::$app->params['site_name'];


    }

    public function beforeAction($action)
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(Url::to(['oauth/index', 'forword' => urlencode(Url::current([], true))], true))->send();
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub

    }

    /**
     * 标签列表查询以及用户所有的标签
     * Renders the index view for the module
     * @return string
     */
    public function actionIndex()
    {
        $dataProvider = EjiaotiebiaoqianLabels::LabelsLists();
        $dataProvider = $dataProvider->getModels();
        $openId = Yii::$app->user->identity->id;
        $myLabels = EjiaotiebiaoqianSelflabels::MyLabels($openId);
        $labels = $myLabels ? $myLabels->labels : '';
        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'labels' => $labels
        ]);

    }

    /**
     *用户选择标签保存
     * @return string
     */
    public function actionCreate()
    {
        $model = new EjiaotiebiaoqianSelflabels();
        $model->myself = Yii::$app->user->identity->openid;
        if ($model->load(Yii::$app->request->post(), '') && $model->save()) {
            return $this->redirect('harem');
        } else {
            return $this->redirect('index');
        }
    }

    /**
     * 我的后宫
     * @return string
     */
    public function actionHarem()
    {
        $friends = EjiaotiebiaoqianFriends::Friends();
        return $this->render('harem', [
            'friends' => $friends,
            'myself' => Yii::$app->user->identity->openid,
        ]);
    }

    /**
     * 抽奖页面渲染
     * @return string
     */
    public function actionLottery()
    {
        return $this->render('lottery');
    }

    /**
     * Renders the index view for the module 抽奖
     * @return string
     */
    public function actionLotteryRun()
    {
        //抽奖
        $result = Lottery::run();

        return Json::encode($result,true);
    }

    /**
     * Renders the index view for the module 领奖
     * @return string
     */
    public function actionReceive()
    {
        if (Yii::$app->user->isGuest) {
            return false;
        }
        $model = new EjiaotiebiaoqianUserinfo();
        if ($model->load(Yii::$app->request->get(), '') && $model->save()) {
            $result = [
                'code' => 0,
                'desc' => '添加成功',
            ];
        } else {
            $result = [
                'code' => 1,
                'desc' => $model->getErrors(),
            ];
        }
        return Json::encode($result);
    }
}
